
export const constants = {
    METHOD: { GET: 'GET', POST: 'POST', PUT: 'PUT', DELETE: 'DELETE' },
    FROM_DATA_PATH: 'INCIDENT_COTROLLER',
    GET_ALL_INCIDENTS_SUCCESS: 'GET_ALL_INCIDENTS_SUCCESS',
    ADD_INCIDENT_SUCCESS: 'ADD_INCIDENT_SUCCESS',
    UPDATE_INCIDENT_SUCCESS: 'UPDATE_INCIDENT_SUCCESS',
    GET_INCIDENT_BY_ID_SUCCESS: 'GET_INCIDENT_BY_ID_SUCCESS',
    INCIDENT_NOT_FOUND: 'INCIDENT_NOT_FOUND',
    ERROR_GETTING_ALL_ICIDETS: 'ERROR_GETTING_ALL_ICIDETS',
    ERROR_ADDING_INCIDENT: 'ERROR_ADDING_INCIDENT'
}

