
export const constants={
    FROM_DATA_PATH : 'INCIDENT_COTROLLER',
    INCIDENT_NOT_FOUND : 'INCIDENT_NOT_FOUND',
    GET_ALL_INCIDENTS_SUCCESS:'GET_ALL_INCIDENTS_SUCCESS',
    ADD_INCIDENT_SUCCESS:'ADD_INCIDENT_SUCCESS',
    UPDATE_INCIDENT_SUCCESS:'UPDATE_INCIDENT_SUCCESS',
    ERROR_GETTING_ALL_ICIDETS:'ERROR_GETTING_ALL_ICIDETS',
    ERROR_ADDING_INCIDENT:'ERROR_ADDING_INCIDENT'
}

