export const constants={
    FROM_DATA_PATH_ERROR : 'FROM_DATA_PATH_ERROR',
    CANDIDATE_NOT_FOUND : 'INCIDENT_NOT_FOUND',
    ERROR_GETTING_ALL_INCIDENTS:'ERROR_GETTING_ALL_INCIDENTS',
    ERROR_UPDATING_INCIDENT:'ERROR_UPDATING_INCIDENT',
    ERROE_ADDING_INCIDENT:'ERROE_ADDING_INCIDENT',
  }